apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: icyujf18g-python 
  janus-idp.io/tekton: icyujf18g-python
  backstage.io/kubernetes-id: icyujf18g-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: icyujf18g-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml